name: Auto PR from Content Branch

on:
  push:
    branches:
      - 'auto/content-*'

permissions:
  contents: write
  pull-requests: write

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "📝 Konten Baru: ${{ github.ref_name }}"
          body: "Konten baru siap direview."
          base: main
          branch: ${{ github.ref_name }}
